name: SidebarManager
version: ${project.version}
author: Luck
main: me.lucko.sidebarmanager.SidebarPlugin
commands:
  sidebar:
    description: Reload configs
    usage: /sidebar
permissions:
  sidebarmanager.reload:
    description: Permission needed to reload the config
    defualt: op